package Home.basics.threads;

public class ResultTask  extends Thread{
    @Override
    public void run(){
        System.out.println("Result generated by: " + Thread.currentThread().getName());
    }

    public static void main(String[] args) {
        ResultTask t1 = new ResultTask();
        t1.run();// ❌ No new thread created
        t1.start(); //✅ new thread is created (Thread-0)
    }
}
/*
ℹ️points to remember
⭐ start() ➡️ Multithreading - Mulitasking - Concurrency
⭐ run()   ➡️ Normal Execution
⭐ start() ➡️ Internally calls run()
⭐ Thread cannot be started twice.
⭐
⭐
⭐
⭐
⭐
 */
